-- The Undo Journal: a row-level history of every journaled table, written by triggers.
--
-- Ctrl+Z reverses a Gesture, and the record it reverses from is written here. The recording is
-- done by SQL triggers rather than by the commands, because there are 83 mutating commands and an
-- inverse written per command is a correctness obligation that has to be met 83 times and then
-- again by every command written afterwards. A trigger cannot be forgotten by a command that does
-- not know it exists. See docs/adr/0006-undo-via-a-trigger-written-row-journal.md.
--
-- This migration only *adds* — two tables, one index and three triggers per journaled table. It
-- rewrites no existing table and moves no data, so the RENAME-and-recreate hazard that cost this
-- repository every tag and dependency edge once before does not arise here: with foreign keys on
-- (database::connect's after_connect), PRAGMA legacy_alter_table has no effect and
-- defer_foreign_keys defers violations rather than cascade actions. Nothing below touches a
-- parent row, so nothing cascades.
--
-- Numbering: 0026-0029 are deliberately left free for branches already in flight.

-- The ambient write context the triggers consult, and the only row of it.
--
-- A trigger has no arguments: it can only read what the schema already holds. So the three things
-- a journal entry needs that the row itself cannot supply — which Gesture the write belongs to,
-- who caused it, and whether journalling is suppressed — live in one row that every trigger reads.
--
-- `gesture_id` is NULL when no Gesture is open. Writes then land in the journal ungrouped, and an
-- ungrouped entry is never offered as an undo step: forgetting to open a Gesture makes a change
-- un-undoable, never makes Ctrl+Z reverse the wrong thing.
--
-- `depth` counts nested opens so that a Gesture spanning several commands is not closed by the
-- first of them — the same "join the caller's boundary, never open your own" rule ADR 0004 gives
-- transactions. It is pinned to gesture_id by a CHECK: depth 0 iff no Gesture.
--
-- `source` has no CHECK listing its values on purpose. It is an enum in Rust (undo::WriteSource),
-- so a third source later is a Rust change and not a migration.
--
-- `suppressed` is set by the undo path for the duration of its own transaction, so that applying
-- an inverse writes no journal entries. Because the write that sets it takes SQLite's single
-- writer lock, a transaction that sets it holds that lock until it commits, and no other
-- connection's write can be journalled — or fail to be — under someone else's flag.
CREATE TABLE undo_context (
    id         INTEGER PRIMARY KEY CHECK (id = 1),
    gesture_id TEXT,
    depth      INTEGER NOT NULL DEFAULT 0 CHECK (depth >= 0),
    source     TEXT NOT NULL DEFAULT 'user',
    suppressed INTEGER NOT NULL DEFAULT 0 CHECK (suppressed IN (0, 1)),
    CHECK ((gesture_id IS NULL) = (depth = 0))
);

INSERT INTO undo_context (id) VALUES (1);

-- One entry per journaled row change.
--
-- Row images are JSON so that one schema serves every table: undo speaks in rows, not in the
-- intent behind them. `row_id` is the SQLite rowid rather than a primary key, because six of the
-- journaled tables have a composite primary key and no id column at all.
--
-- `seq` is AUTOINCREMENT: it is the total order undo walks backwards, and plain rowid reuse after
-- a prune could put a later entry before an earlier one.
--
-- The journal is session-scoped — truncated at startup and capped at a depth — so it needs no
-- retention policy and holds nothing across runs.
CREATE TABLE undo_journal (
    seq          INTEGER PRIMARY KEY AUTOINCREMENT,
    gesture_id   TEXT,
    source       TEXT NOT NULL,
    table_name   TEXT NOT NULL,
    row_id       INTEGER NOT NULL,
    operation    TEXT NOT NULL CHECK (operation IN ('insert', 'update', 'delete')),
    before_image TEXT,
    after_image  TEXT,
    written_at   TEXT NOT NULL,
    -- An insert has nothing before it and a delete has nothing after it; an update has both.
    CHECK ((operation = 'insert') = (before_image IS NULL)),
    CHECK ((operation = 'delete') = (after_image IS NULL))
);

CREATE INDEX idx_undo_journal_gesture ON undo_journal (gesture_id, seq);

-- Three triggers per journaled table, generated by scripts/generate-undo-triggers.sh from the
-- schema as of this migration. Every column of the table is named in the image, so a column added
-- later is not journaled until the triggers are regenerated into a new migration — which is what
-- tests/undo_journal.rs checks, column by column, rather than merely counting triggers.
--
-- `scopes` is excluded and is the only domain table that is. A scope row is not authored: it is
-- the calendar, instantiated on demand by ScopeOperator::get_or_create and deduplicated by the
-- three uniqueness indexes over it. Nothing in the codebase ever deletes one. Journalling scopes
-- would mean undo deleting a row that get_or_create will simply recreate — and, worse, deleting
-- one that another item still references, which with foreign keys on fails the undo itself.
-- undo_context and undo_journal are excluded because journalling the journal is a loop.

CREATE TRIGGER undo_journal_block_reasons_insert AFTER INSERT ON block_reasons BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'block_reasons', new.rowid, 'insert', NULL, json_object('id', new.id, 'owner_type', new.owner_type, 'owner_id', new.owner_id, 'reason', new.reason, 'position', new.position, 'created_at', new.created_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_block_reasons_update AFTER UPDATE ON block_reasons BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'block_reasons', new.rowid, 'update', json_object('id', old.id, 'owner_type', old.owner_type, 'owner_id', old.owner_id, 'reason', old.reason, 'position', old.position, 'created_at', old.created_at), json_object('id', new.id, 'owner_type', new.owner_type, 'owner_id', new.owner_id, 'reason', new.reason, 'position', new.position, 'created_at', new.created_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_block_reasons_delete AFTER DELETE ON block_reasons BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'block_reasons', old.rowid, 'delete', json_object('id', old.id, 'owner_type', old.owner_type, 'owner_id', old.owner_id, 'reason', old.reason, 'position', old.position, 'created_at', old.created_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_domains_insert AFTER INSERT ON domains BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'domains', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'description', new.description, 'subtype', new.subtype, 'parent_id', new.parent_id, 'color', new.color, 'status', new.status, 'knowledge_base_directory', new.knowledge_base_directory, 'position', new.position, 'is_private', new.is_private, 'beads_id', new.beads_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_domains_update AFTER UPDATE ON domains BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'domains', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'description', old.description, 'subtype', old.subtype, 'parent_id', old.parent_id, 'color', old.color, 'status', old.status, 'knowledge_base_directory', old.knowledge_base_directory, 'position', old.position, 'is_private', old.is_private, 'beads_id', old.beads_id), json_object('id', new.id, 'title', new.title, 'description', new.description, 'subtype', new.subtype, 'parent_id', new.parent_id, 'color', new.color, 'status', new.status, 'knowledge_base_directory', new.knowledge_base_directory, 'position', new.position, 'is_private', new.is_private, 'beads_id', new.beads_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_domains_delete AFTER DELETE ON domains BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'domains', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'description', old.description, 'subtype', old.subtype, 'parent_id', old.parent_id, 'color', old.color, 'status', old.status, 'knowledge_base_directory', old.knowledge_base_directory, 'position', old.position, 'is_private', old.is_private, 'beads_id', old.beads_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_events_insert AFTER INSERT ON events BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'events', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'scope_id', new.scope_id, 'event_time', new.event_time, 'linked_note', new.linked_note), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_events_update AFTER UPDATE ON events BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'events', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'scope_id', old.scope_id, 'event_time', old.event_time, 'linked_note', old.linked_note), json_object('id', new.id, 'title', new.title, 'scope_id', new.scope_id, 'event_time', new.event_time, 'linked_note', new.linked_note), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_events_delete AFTER DELETE ON events BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'events', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'scope_id', old.scope_id, 'event_time', old.event_time, 'linked_note', old.linked_note), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_dependencies_insert AFTER INSERT ON flow_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_dependencies', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'dependent_type', new.dependent_type, 'dependent_id', new.dependent_id, 'depends_on_type', new.depends_on_type, 'depends_on_id', new.depends_on_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_dependencies_update AFTER UPDATE ON flow_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_dependencies', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'dependent_type', old.dependent_type, 'dependent_id', old.dependent_id, 'depends_on_type', old.depends_on_type, 'depends_on_id', old.depends_on_id), json_object('id', new.id, 'flow_id', new.flow_id, 'dependent_type', new.dependent_type, 'dependent_id', new.dependent_id, 'depends_on_type', new.depends_on_type, 'depends_on_id', new.depends_on_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_dependencies_delete AFTER DELETE ON flow_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_dependencies', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'dependent_type', old.dependent_type, 'dependent_id', old.dependent_id, 'depends_on_type', old.depends_on_type, 'depends_on_id', old.depends_on_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_goals_insert AFTER INSERT ON flow_goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_goals', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'position', new.position, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_goals_update AFTER UPDATE ON flow_goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_goals', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'position', old.position, 'is_private', old.is_private), json_object('id', new.id, 'flow_id', new.flow_id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'position', new.position, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_goals_delete AFTER DELETE ON flow_goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_goals', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'position', old.position, 'is_private', old.is_private), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_instance_nodes_insert AFTER INSERT ON flow_instance_nodes BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_instance_nodes', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_instance_id', new.flow_instance_id, 'node_type', new.node_type, 'node_id', new.node_id, 'source_item_type', new.source_item_type, 'source_item_id', new.source_item_id, 'original_parent_type', new.original_parent_type, 'original_parent_id', new.original_parent_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_instance_nodes_update AFTER UPDATE ON flow_instance_nodes BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_instance_nodes', new.rowid, 'update', json_object('id', old.id, 'flow_instance_id', old.flow_instance_id, 'node_type', old.node_type, 'node_id', old.node_id, 'source_item_type', old.source_item_type, 'source_item_id', old.source_item_id, 'original_parent_type', old.original_parent_type, 'original_parent_id', old.original_parent_id), json_object('id', new.id, 'flow_instance_id', new.flow_instance_id, 'node_type', new.node_type, 'node_id', new.node_id, 'source_item_type', new.source_item_type, 'source_item_id', new.source_item_id, 'original_parent_type', new.original_parent_type, 'original_parent_id', new.original_parent_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_instance_nodes_delete AFTER DELETE ON flow_instance_nodes BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_instance_nodes', old.rowid, 'delete', json_object('id', old.id, 'flow_instance_id', old.flow_instance_id, 'node_type', old.node_type, 'node_id', old.node_id, 'source_item_type', old.source_item_type, 'source_item_id', old.source_item_id, 'original_parent_type', old.original_parent_type, 'original_parent_id', old.original_parent_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_instances_insert AFTER INSERT ON flow_instances BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_instances', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'root_type', new.root_type, 'root_id', new.root_id, 'started_at', new.started_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_instances_update AFTER UPDATE ON flow_instances BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_instances', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'root_type', old.root_type, 'root_id', old.root_id, 'started_at', old.started_at), json_object('id', new.id, 'flow_id', new.flow_id, 'root_type', new.root_type, 'root_id', new.root_id, 'started_at', new.started_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_instances_delete AFTER DELETE ON flow_instances BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_instances', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'root_type', old.root_type, 'root_id', old.root_id, 'started_at', old.started_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_item_cycles_insert AFTER INSERT ON flow_item_cycles BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_item_cycles', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'item_type', new.item_type, 'item_id', new.item_id, 'scope_kind', new.scope_kind, 'scope_index', new.scope_index, 'plan_kind', new.plan_kind, 'plan_start', new.plan_start, 'plan_end', new.plan_end, 'position', new.position), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_item_cycles_update AFTER UPDATE ON flow_item_cycles BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_item_cycles', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'item_type', old.item_type, 'item_id', old.item_id, 'scope_kind', old.scope_kind, 'scope_index', old.scope_index, 'plan_kind', old.plan_kind, 'plan_start', old.plan_start, 'plan_end', old.plan_end, 'position', old.position), json_object('id', new.id, 'flow_id', new.flow_id, 'item_type', new.item_type, 'item_id', new.item_id, 'scope_kind', new.scope_kind, 'scope_index', new.scope_index, 'plan_kind', new.plan_kind, 'plan_start', new.plan_start, 'plan_end', new.plan_end, 'position', new.position), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_item_cycles_delete AFTER DELETE ON flow_item_cycles BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_item_cycles', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'item_type', old.item_type, 'item_id', old.item_id, 'scope_kind', old.scope_kind, 'scope_index', old.scope_index, 'plan_kind', old.plan_kind, 'plan_start', old.plan_start, 'plan_end', old.plan_end, 'position', old.position), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_recurrences_insert AFTER INSERT ON flow_recurrences BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_recurrences', new.rowid, 'insert', NULL, json_object('flow_id', new.flow_id, 'start_scope_id', new.start_scope_id, 'gap_n', new.gap_n, 'gap_kind', new.gap_kind, 'end_scope_id', new.end_scope_id, 'consumption_kind', new.consumption_kind, 'blocking_mode', new.blocking_mode, 'catchup_policy', new.catchup_policy), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_recurrences_update AFTER UPDATE ON flow_recurrences BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_recurrences', new.rowid, 'update', json_object('flow_id', old.flow_id, 'start_scope_id', old.start_scope_id, 'gap_n', old.gap_n, 'gap_kind', old.gap_kind, 'end_scope_id', old.end_scope_id, 'consumption_kind', old.consumption_kind, 'blocking_mode', old.blocking_mode, 'catchup_policy', old.catchup_policy), json_object('flow_id', new.flow_id, 'start_scope_id', new.start_scope_id, 'gap_n', new.gap_n, 'gap_kind', new.gap_kind, 'end_scope_id', new.end_scope_id, 'consumption_kind', new.consumption_kind, 'blocking_mode', new.blocking_mode, 'catchup_policy', new.catchup_policy), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_recurrences_delete AFTER DELETE ON flow_recurrences BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_recurrences', old.rowid, 'delete', json_object('flow_id', old.flow_id, 'start_scope_id', old.start_scope_id, 'gap_n', old.gap_n, 'gap_kind', old.gap_kind, 'end_scope_id', old.end_scope_id, 'consumption_kind', old.consumption_kind, 'blocking_mode', old.blocking_mode, 'catchup_policy', old.catchup_policy), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_tasks_insert AFTER INSERT ON flow_tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_tasks', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'position', new.position, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_tasks_update AFTER UPDATE ON flow_tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_tasks', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'position', old.position, 'is_private', old.is_private), json_object('id', new.id, 'flow_id', new.flow_id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'position', new.position, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_tasks_delete AFTER DELETE ON flow_tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_tasks', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'position', old.position, 'is_private', old.is_private), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flows_insert AFTER INSERT ON flows BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flows', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'instance_type', new.instance_type, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'target_type', new.target_type, 'target_id', new.target_id, 'flow_duration_n', new.flow_duration_n, 'flow_duration_kind', new.flow_duration_kind, 'position', new.position, 'flow_window_part', new.flow_window_part, 'flow_window_time_start', new.flow_window_time_start, 'flow_window_time_end', new.flow_window_time_end, 'root_plan_kind', new.root_plan_kind, 'root_plan_start', new.root_plan_start, 'root_plan_end', new.root_plan_end, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flows_update AFTER UPDATE ON flows BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flows', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'instance_type', old.instance_type, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'target_type', old.target_type, 'target_id', old.target_id, 'flow_duration_n', old.flow_duration_n, 'flow_duration_kind', old.flow_duration_kind, 'position', old.position, 'flow_window_part', old.flow_window_part, 'flow_window_time_start', old.flow_window_time_start, 'flow_window_time_end', old.flow_window_time_end, 'root_plan_kind', old.root_plan_kind, 'root_plan_start', old.root_plan_start, 'root_plan_end', old.root_plan_end, 'is_private', old.is_private), json_object('id', new.id, 'title', new.title, 'instance_type', new.instance_type, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'target_type', new.target_type, 'target_id', new.target_id, 'flow_duration_n', new.flow_duration_n, 'flow_duration_kind', new.flow_duration_kind, 'position', new.position, 'flow_window_part', new.flow_window_part, 'flow_window_time_start', new.flow_window_time_start, 'flow_window_time_end', new.flow_window_time_end, 'root_plan_kind', new.root_plan_kind, 'root_plan_start', new.root_plan_start, 'root_plan_end', new.root_plan_end, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flows_delete AFTER DELETE ON flows BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flows', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'instance_type', old.instance_type, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'target_type', old.target_type, 'target_id', old.target_id, 'flow_duration_n', old.flow_duration_n, 'flow_duration_kind', old.flow_duration_kind, 'position', old.position, 'flow_window_part', old.flow_window_part, 'flow_window_time_start', old.flow_window_time_start, 'flow_window_time_end', old.flow_window_time_end, 'root_plan_kind', old.root_plan_kind, 'root_plan_start', old.root_plan_start, 'root_plan_end', old.root_plan_end, 'is_private', old.is_private), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goal_knowledge_base_links_insert AFTER INSERT ON goal_knowledge_base_links BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goal_knowledge_base_links', new.rowid, 'insert', NULL, json_object('goal_id', new.goal_id, 'entity_type', new.entity_type, 'entity_id', new.entity_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goal_knowledge_base_links_update AFTER UPDATE ON goal_knowledge_base_links BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goal_knowledge_base_links', new.rowid, 'update', json_object('goal_id', old.goal_id, 'entity_type', old.entity_type, 'entity_id', old.entity_id), json_object('goal_id', new.goal_id, 'entity_type', new.entity_type, 'entity_id', new.entity_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goal_knowledge_base_links_delete AFTER DELETE ON goal_knowledge_base_links BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goal_knowledge_base_links', old.rowid, 'delete', json_object('goal_id', old.goal_id, 'entity_type', old.entity_type, 'entity_id', old.entity_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goals_insert AFTER INSERT ON goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goals', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'position', new.position, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'on_scope_exit', new.on_scope_exit, 'is_private', new.is_private, 'beads_id', new.beads_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goals_update AFTER UPDATE ON goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goals', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'position', old.position, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'on_scope_exit', old.on_scope_exit, 'is_private', old.is_private, 'beads_id', old.beads_id), json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'position', new.position, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'on_scope_exit', new.on_scope_exit, 'is_private', new.is_private, 'beads_id', new.beads_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goals_delete AFTER DELETE ON goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goals', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'position', old.position, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'on_scope_exit', old.on_scope_exit, 'is_private', old.is_private, 'beads_id', old.beads_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_habit_instance_dependencies_insert AFTER INSERT ON habit_instance_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_dependencies', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'iteration_scope_id', new.iteration_scope_id, 'dependent_type', new.dependent_type, 'dependent_id', new.dependent_id, 'depends_on_type', new.depends_on_type, 'depends_on_id', new.depends_on_id, 'added', new.added), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_habit_instance_dependencies_update AFTER UPDATE ON habit_instance_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_dependencies', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'iteration_scope_id', old.iteration_scope_id, 'dependent_type', old.dependent_type, 'dependent_id', old.dependent_id, 'depends_on_type', old.depends_on_type, 'depends_on_id', old.depends_on_id, 'added', old.added), json_object('id', new.id, 'flow_id', new.flow_id, 'iteration_scope_id', new.iteration_scope_id, 'dependent_type', new.dependent_type, 'dependent_id', new.dependent_id, 'depends_on_type', new.depends_on_type, 'depends_on_id', new.depends_on_id, 'added', new.added), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_habit_instance_dependencies_delete AFTER DELETE ON habit_instance_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_dependencies', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'iteration_scope_id', old.iteration_scope_id, 'dependent_type', old.dependent_type, 'dependent_id', old.dependent_id, 'depends_on_type', old.depends_on_type, 'depends_on_id', old.depends_on_id, 'added', old.added), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_habit_instance_modifications_insert AFTER INSERT ON habit_instance_modifications BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_modifications', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'item_type', new.item_type, 'item_id', new.item_id, 'iteration_scope_id', new.iteration_scope_id, 'status', new.status, 'title', new.title, 'blocked_reason', new.blocked_reason, 'tombstone_kind', new.tombstone_kind, 'resolved_at', new.resolved_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_habit_instance_modifications_update AFTER UPDATE ON habit_instance_modifications BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_modifications', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'item_type', old.item_type, 'item_id', old.item_id, 'iteration_scope_id', old.iteration_scope_id, 'status', old.status, 'title', old.title, 'blocked_reason', old.blocked_reason, 'tombstone_kind', old.tombstone_kind, 'resolved_at', old.resolved_at), json_object('id', new.id, 'flow_id', new.flow_id, 'item_type', new.item_type, 'item_id', new.item_id, 'iteration_scope_id', new.iteration_scope_id, 'status', new.status, 'title', new.title, 'blocked_reason', new.blocked_reason, 'tombstone_kind', new.tombstone_kind, 'resolved_at', new.resolved_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_habit_instance_modifications_delete AFTER DELETE ON habit_instance_modifications BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_modifications', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'item_type', old.item_type, 'item_id', old.item_id, 'iteration_scope_id', old.iteration_scope_id, 'status', old.status, 'title', old.title, 'blocked_reason', old.blocked_reason, 'tombstone_kind', old.tombstone_kind, 'resolved_at', old.resolved_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_infos_insert AFTER INSERT ON infos BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'infos', new.rowid, 'insert', NULL, json_object('id', new.id, 'body', new.body, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'position', new.position, 'created_at', new.created_at, 'updated_at', new.updated_at, 'details', new.details, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_infos_update AFTER UPDATE ON infos BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'infos', new.rowid, 'update', json_object('id', old.id, 'body', old.body, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'position', old.position, 'created_at', old.created_at, 'updated_at', old.updated_at, 'details', old.details, 'is_private', old.is_private), json_object('id', new.id, 'body', new.body, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'position', new.position, 'created_at', new.created_at, 'updated_at', new.updated_at, 'details', new.details, 'is_private', new.is_private), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_infos_delete AFTER DELETE ON infos BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'infos', old.rowid, 'delete', json_object('id', old.id, 'body', old.body, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'position', old.position, 'created_at', old.created_at, 'updated_at', old.updated_at, 'details', old.details, 'is_private', old.is_private), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_people_insert AFTER INSERT ON people BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'people', new.rowid, 'insert', NULL, json_object('id', new.id, 'name', new.name, 'aliases', new.aliases, 'linked_note', new.linked_note), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_people_update AFTER UPDATE ON people BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'people', new.rowid, 'update', json_object('id', old.id, 'name', old.name, 'aliases', old.aliases, 'linked_note', old.linked_note), json_object('id', new.id, 'name', new.name, 'aliases', new.aliases, 'linked_note', new.linked_note), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_people_delete AFTER DELETE ON people BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'people', old.rowid, 'delete', json_object('id', old.id, 'name', old.name, 'aliases', old.aliases, 'linked_note', old.linked_note), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tags_on_goals_insert AFTER INSERT ON tags_on_goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tags_on_goals', new.rowid, 'insert', NULL, json_object('goal_id', new.goal_id, 'tag_id', new.tag_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tags_on_goals_update AFTER UPDATE ON tags_on_goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tags_on_goals', new.rowid, 'update', json_object('goal_id', old.goal_id, 'tag_id', old.tag_id), json_object('goal_id', new.goal_id, 'tag_id', new.tag_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tags_on_goals_delete AFTER DELETE ON tags_on_goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tags_on_goals', old.rowid, 'delete', json_object('goal_id', old.goal_id, 'tag_id', old.tag_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tags_on_tasks_insert AFTER INSERT ON tags_on_tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tags_on_tasks', new.rowid, 'insert', NULL, json_object('task_id', new.task_id, 'tag_id', new.tag_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tags_on_tasks_update AFTER UPDATE ON tags_on_tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tags_on_tasks', new.rowid, 'update', json_object('task_id', old.task_id, 'tag_id', old.tag_id), json_object('task_id', new.task_id, 'tag_id', new.tag_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tags_on_tasks_delete AFTER DELETE ON tags_on_tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tags_on_tasks', old.rowid, 'delete', json_object('task_id', old.task_id, 'tag_id', old.tag_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_task_dependencies_insert AFTER INSERT ON task_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'task_dependencies', new.rowid, 'insert', NULL, json_object('task_id', new.task_id, 'dependency_type', new.dependency_type, 'dependency_id', new.dependency_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_task_dependencies_update AFTER UPDATE ON task_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'task_dependencies', new.rowid, 'update', json_object('task_id', old.task_id, 'dependency_type', old.dependency_type, 'dependency_id', old.dependency_id), json_object('task_id', new.task_id, 'dependency_type', new.dependency_type, 'dependency_id', new.dependency_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_task_dependencies_delete AFTER DELETE ON task_dependencies BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'task_dependencies', old.rowid, 'delete', json_object('task_id', old.task_id, 'dependency_type', old.dependency_type, 'dependency_id', old.dependency_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_task_knowledge_base_links_insert AFTER INSERT ON task_knowledge_base_links BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'task_knowledge_base_links', new.rowid, 'insert', NULL, json_object('task_id', new.task_id, 'entity_type', new.entity_type, 'entity_id', new.entity_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_task_knowledge_base_links_update AFTER UPDATE ON task_knowledge_base_links BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'task_knowledge_base_links', new.rowid, 'update', json_object('task_id', old.task_id, 'entity_type', old.entity_type, 'entity_id', old.entity_id), json_object('task_id', new.task_id, 'entity_type', new.entity_type, 'entity_id', new.entity_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_task_knowledge_base_links_delete AFTER DELETE ON task_knowledge_base_links BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'task_knowledge_base_links', old.rowid, 'delete', json_object('task_id', old.task_id, 'entity_type', old.entity_type, 'entity_id', old.entity_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tasks_insert AFTER INSERT ON tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tasks', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'delegate_to', new.delegate_to, 'position', new.position, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'plan_start_id', new.plan_start_id, 'plan_end_id', new.plan_end_id, 'on_scope_exit', new.on_scope_exit, 'is_private', new.is_private, 'beads_id', new.beads_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tasks_update AFTER UPDATE ON tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tasks', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'delegate_to', old.delegate_to, 'position', old.position, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'plan_start_id', old.plan_start_id, 'plan_end_id', old.plan_end_id, 'on_scope_exit', old.on_scope_exit, 'is_private', old.is_private, 'beads_id', old.beads_id), json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'delegate_to', new.delegate_to, 'position', new.position, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'plan_start_id', new.plan_start_id, 'plan_end_id', new.plan_end_id, 'on_scope_exit', new.on_scope_exit, 'is_private', new.is_private, 'beads_id', new.beads_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_tasks_delete AFTER DELETE ON tasks BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'tasks', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'delegate_to', old.delegate_to, 'position', old.position, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'plan_start_id', old.plan_start_id, 'plan_end_id', old.plan_end_id, 'on_scope_exit', old.on_scope_exit, 'is_private', old.is_private, 'beads_id', old.beads_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_threads_insert AFTER INSERT ON threads BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'threads', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'linked_note', new.linked_note), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_threads_update AFTER UPDATE ON threads BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'threads', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'linked_note', old.linked_note), json_object('id', new.id, 'title', new.title, 'linked_note', new.linked_note), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_threads_delete AFTER DELETE ON threads BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'threads', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'linked_note', old.linked_note), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;
