-- Regenerate the undo-journal triggers for `habit_instance_modifications`, which gained
-- `plan_overridden`, `plan_start_id` and `plan_end_id` in 0035.
--
-- A journal trigger names every column of its table by hand, so a column added afterwards is not
-- in the row image and undo would restore it to whatever the other columns' image carried —
-- silently. Undoing "plan this occurrence for Saturday" has to put the occurrence back on its Cycle
-- Plan, which only happens if the three new columns are in the image. Generated by
-- scripts/generate-undo-triggers.sh; a separate migration after the ALTER, per 0032's rule.

DROP TRIGGER IF EXISTS undo_journal_habit_instance_modifications_insert;
CREATE TRIGGER undo_journal_habit_instance_modifications_insert AFTER INSERT ON habit_instance_modifications BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_modifications', new.rowid, 'insert', NULL, json_object('id', new.id, 'flow_id', new.flow_id, 'item_type', new.item_type, 'item_id', new.item_id, 'iteration_scope_id', new.iteration_scope_id, 'cycle_id', new.cycle_id, 'status', new.status, 'title', new.title, 'blocked_reason', new.blocked_reason, 'tombstone_kind', new.tombstone_kind, 'resolved_at', new.resolved_at, 'plan_overridden', new.plan_overridden, 'plan_start_id', new.plan_start_id, 'plan_end_id', new.plan_end_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

DROP TRIGGER IF EXISTS undo_journal_habit_instance_modifications_update;
CREATE TRIGGER undo_journal_habit_instance_modifications_update AFTER UPDATE ON habit_instance_modifications BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_modifications', new.rowid, 'update', json_object('id', old.id, 'flow_id', old.flow_id, 'item_type', old.item_type, 'item_id', old.item_id, 'iteration_scope_id', old.iteration_scope_id, 'cycle_id', old.cycle_id, 'status', old.status, 'title', old.title, 'blocked_reason', old.blocked_reason, 'tombstone_kind', old.tombstone_kind, 'resolved_at', old.resolved_at, 'plan_overridden', old.plan_overridden, 'plan_start_id', old.plan_start_id, 'plan_end_id', old.plan_end_id), json_object('id', new.id, 'flow_id', new.flow_id, 'item_type', new.item_type, 'item_id', new.item_id, 'iteration_scope_id', new.iteration_scope_id, 'cycle_id', new.cycle_id, 'status', new.status, 'title', new.title, 'blocked_reason', new.blocked_reason, 'tombstone_kind', new.tombstone_kind, 'resolved_at', new.resolved_at, 'plan_overridden', new.plan_overridden, 'plan_start_id', new.plan_start_id, 'plan_end_id', new.plan_end_id), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

DROP TRIGGER IF EXISTS undo_journal_habit_instance_modifications_delete;
CREATE TRIGGER undo_journal_habit_instance_modifications_delete AFTER DELETE ON habit_instance_modifications BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'habit_instance_modifications', old.rowid, 'delete', json_object('id', old.id, 'flow_id', old.flow_id, 'item_type', old.item_type, 'item_id', old.item_id, 'iteration_scope_id', old.iteration_scope_id, 'cycle_id', old.cycle_id, 'status', old.status, 'title', old.title, 'blocked_reason', old.blocked_reason, 'tombstone_kind', old.tombstone_kind, 'resolved_at', old.resolved_at, 'plan_overridden', old.plan_overridden, 'plan_start_id', old.plan_start_id, 'plan_end_id', old.plan_end_id), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;
