-- Habit cooldown (Task 199): a Window Habit may carry a cooldown — N units of a scope kind finer
-- than the habit's own (a weekly habit's in days, a monthly one's in weeks or days, a daily one's
-- in parts of the day). After an iteration is done, the next one — under Owed, every one still
-- open — is blocked until the cooldown has passed (docs/spec/habits.md, "Cooldown").
--
-- Two nullable columns, set together, and only on a Window clock: an Interval's Gap already counts
-- from completion. Every existing Habit has none, so nothing is rewritten.

ALTER TABLE flow_recurrences ADD COLUMN cooldown_n INTEGER
    CHECK (cooldown_n IS NULL OR cooldown_n >= 1);
ALTER TABLE flow_recurrences ADD COLUMN cooldown_kind TEXT
    CHECK ((cooldown_kind IS NULL) = (cooldown_n IS NULL)
           AND (cooldown_kind IS NULL OR (cooldown_kind IN ('part', 'day', 'week', 'month')
                                          AND clock = 'window')));

-- The undo journal's images name every column, so the three `flow_recurrences` triggers are
-- rebuilt with the two new ones.
DROP TRIGGER undo_journal_flow_recurrences_insert;
DROP TRIGGER undo_journal_flow_recurrences_update;
DROP TRIGGER undo_journal_flow_recurrences_delete;

CREATE TRIGGER undo_journal_flow_recurrences_insert AFTER INSERT ON flow_recurrences BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_recurrences', new.rowid, 'insert', NULL, json_object('flow_id', new.flow_id, 'start_scope_id', new.start_scope_id, 'gap_n', new.gap_n, 'gap_kind', new.gap_kind, 'end_scope_id', new.end_scope_id, 'clock', new.clock, 'miss_policy', new.miss_policy, 'cooldown_n', new.cooldown_n, 'cooldown_kind', new.cooldown_kind), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_recurrences_update AFTER UPDATE ON flow_recurrences BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_recurrences', new.rowid, 'update', json_object('flow_id', old.flow_id, 'start_scope_id', old.start_scope_id, 'gap_n', old.gap_n, 'gap_kind', old.gap_kind, 'end_scope_id', old.end_scope_id, 'clock', old.clock, 'miss_policy', old.miss_policy, 'cooldown_n', old.cooldown_n, 'cooldown_kind', old.cooldown_kind), json_object('flow_id', new.flow_id, 'start_scope_id', new.start_scope_id, 'gap_n', new.gap_n, 'gap_kind', new.gap_kind, 'end_scope_id', new.end_scope_id, 'clock', new.clock, 'miss_policy', new.miss_policy, 'cooldown_n', new.cooldown_n, 'cooldown_kind', new.cooldown_kind), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_flow_recurrences_delete AFTER DELETE ON flow_recurrences BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'flow_recurrences', old.rowid, 'delete', json_object('flow_id', old.flow_id, 'start_scope_id', old.start_scope_id, 'gap_n', old.gap_n, 'gap_kind', old.gap_kind, 'end_scope_id', old.end_scope_id, 'clock', old.clock, 'miss_policy', old.miss_policy, 'cooldown_n', old.cooldown_n, 'cooldown_kind', old.cooldown_kind), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

-- Completion instants (Task 199, ruled by the user 2026-10-01: commitments may take an Interval and
-- a cooldown, which count from the verdict). A Task's completion is `tasks.done_at` (migration 0044)
-- and an occurrence's its overlay's `resolved_at`; these record the same instant for the other
-- kinds: when a Goal was achieved, when a wait was released, and when a Commitment's verdict was
-- recorded. Written by every path that achieves, releases or records a verdict, kept while that
-- stays so, and cleared when it is undone. Existing rows stay NULL: no history is invented. The
-- Goal and Commitment overlays already carry `resolved_at`; a derived wait's release lives in
-- `spawned_waits` / `occurrence_spawned_waits`, beside its status.
ALTER TABLE goals ADD COLUMN achieved_at TEXT;
ALTER TABLE expectations ADD COLUMN released_at TEXT;
ALTER TABLE commitments ADD COLUMN verdict_at TEXT;
ALTER TABLE spawned_waits ADD COLUMN released_at TEXT;
ALTER TABLE occurrence_spawned_waits ADD COLUMN released_at TEXT;

-- The undo journal's images name every column, so the triggers of the five tables are rebuilt
-- with their new instant (generated by scripts/generate-undo-triggers.sh).
DROP TRIGGER undo_journal_goals_insert;
DROP TRIGGER undo_journal_goals_update;
DROP TRIGGER undo_journal_goals_delete;
DROP TRIGGER undo_journal_expectations_insert;
DROP TRIGGER undo_journal_expectations_update;
DROP TRIGGER undo_journal_expectations_delete;
DROP TRIGGER undo_journal_commitments_insert;
DROP TRIGGER undo_journal_commitments_update;
DROP TRIGGER undo_journal_commitments_delete;
DROP TRIGGER undo_journal_spawned_waits_insert;
DROP TRIGGER undo_journal_spawned_waits_update;
DROP TRIGGER undo_journal_spawned_waits_delete;
DROP TRIGGER undo_journal_occurrence_spawned_waits_insert;
DROP TRIGGER undo_journal_occurrence_spawned_waits_update;
DROP TRIGGER undo_journal_occurrence_spawned_waits_delete;

CREATE TRIGGER undo_journal_goals_insert AFTER INSERT ON goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goals', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'position', new.position, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'on_scope_exit', new.on_scope_exit, 'is_private', new.is_private, 'beads_id', new.beads_id, 'achieved_at', new.achieved_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goals_update AFTER UPDATE ON goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goals', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'position', old.position, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'on_scope_exit', old.on_scope_exit, 'is_private', old.is_private, 'beads_id', old.beads_id, 'achieved_at', old.achieved_at), json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'position', new.position, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'on_scope_exit', new.on_scope_exit, 'is_private', new.is_private, 'beads_id', new.beads_id, 'achieved_at', new.achieved_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_goals_delete AFTER DELETE ON goals BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'goals', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'position', old.position, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'on_scope_exit', old.on_scope_exit, 'is_private', old.is_private, 'beads_id', old.beads_id, 'achieved_at', old.achieved_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_expectations_insert AFTER INSERT ON expectations BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'expectations', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'archival', new.archival, 'position', new.position, 'is_private', new.is_private, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'check_every_n', new.check_every_n, 'check_every_kind', new.check_every_kind, 'check_starting', new.check_starting, 'last_check_at', new.last_check_at, 'agentic', new.agentic, 'agentic_note', new.agentic_note, 'agentic_question', new.agentic_question, 'agentic_answer', new.agentic_answer, 'released_at', new.released_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_expectations_update AFTER UPDATE ON expectations BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'expectations', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'archival', old.archival, 'position', old.position, 'is_private', old.is_private, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'check_every_n', old.check_every_n, 'check_every_kind', old.check_every_kind, 'check_starting', old.check_starting, 'last_check_at', old.last_check_at, 'agentic', old.agentic, 'agentic_note', old.agentic_note, 'agentic_question', old.agentic_question, 'agentic_answer', old.agentic_answer, 'released_at', old.released_at), json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'status', new.status, 'archival', new.archival, 'position', new.position, 'is_private', new.is_private, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'check_every_n', new.check_every_n, 'check_every_kind', new.check_every_kind, 'check_starting', new.check_starting, 'last_check_at', new.last_check_at, 'agentic', new.agentic, 'agentic_note', new.agentic_note, 'agentic_question', new.agentic_question, 'agentic_answer', new.agentic_answer, 'released_at', new.released_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_expectations_delete AFTER DELETE ON expectations BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'expectations', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'status', old.status, 'archival', old.archival, 'position', old.position, 'is_private', old.is_private, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'check_every_n', old.check_every_n, 'check_every_kind', old.check_every_kind, 'check_starting', old.check_starting, 'last_check_at', old.last_check_at, 'agentic', old.agentic, 'agentic_note', old.agentic_note, 'agentic_question', old.agentic_question, 'agentic_answer', old.agentic_answer, 'released_at', old.released_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_commitments_insert AFTER INSERT ON commitments BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'commitments', new.rowid, 'insert', NULL, json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'verdict', new.verdict, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'verdict_window_n', new.verdict_window_n, 'verdict_window_kind', new.verdict_window_kind, 'position', new.position, 'is_private', new.is_private, 'beads_id', new.beads_id, 'verdict_at', new.verdict_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_commitments_update AFTER UPDATE ON commitments BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'commitments', new.rowid, 'update', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'verdict', old.verdict, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'verdict_window_n', old.verdict_window_n, 'verdict_window_kind', old.verdict_window_kind, 'position', old.position, 'is_private', old.is_private, 'beads_id', old.beads_id, 'verdict_at', old.verdict_at), json_object('id', new.id, 'title', new.title, 'parent_type', new.parent_type, 'parent_id', new.parent_id, 'verdict', new.verdict, 'time_scope_start_id', new.time_scope_start_id, 'time_scope_end_id', new.time_scope_end_id, 'time_scope_duration_n', new.time_scope_duration_n, 'time_scope_duration_kind', new.time_scope_duration_kind, 'verdict_window_n', new.verdict_window_n, 'verdict_window_kind', new.verdict_window_kind, 'position', new.position, 'is_private', new.is_private, 'beads_id', new.beads_id, 'verdict_at', new.verdict_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_commitments_delete AFTER DELETE ON commitments BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'commitments', old.rowid, 'delete', json_object('id', old.id, 'title', old.title, 'parent_type', old.parent_type, 'parent_id', old.parent_id, 'verdict', old.verdict, 'time_scope_start_id', old.time_scope_start_id, 'time_scope_end_id', old.time_scope_end_id, 'time_scope_duration_n', old.time_scope_duration_n, 'time_scope_duration_kind', old.time_scope_duration_kind, 'verdict_window_n', old.verdict_window_n, 'verdict_window_kind', old.verdict_window_kind, 'position', old.position, 'is_private', old.is_private, 'beads_id', old.beads_id, 'verdict_at', old.verdict_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_spawned_waits_insert AFTER INSERT ON spawned_waits BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'spawned_waits', new.rowid, 'insert', NULL, json_object('task_id', new.task_id, 'status', new.status, 'archival', new.archival, 'last_check_at', new.last_check_at, 'released_at', new.released_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_spawned_waits_update AFTER UPDATE ON spawned_waits BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'spawned_waits', new.rowid, 'update', json_object('task_id', old.task_id, 'status', old.status, 'archival', old.archival, 'last_check_at', old.last_check_at, 'released_at', old.released_at), json_object('task_id', new.task_id, 'status', new.status, 'archival', new.archival, 'last_check_at', new.last_check_at, 'released_at', new.released_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_spawned_waits_delete AFTER DELETE ON spawned_waits BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'spawned_waits', old.rowid, 'delete', json_object('task_id', old.task_id, 'status', old.status, 'archival', old.archival, 'last_check_at', old.last_check_at, 'released_at', old.released_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_occurrence_spawned_waits_insert AFTER INSERT ON occurrence_spawned_waits BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'occurrence_spawned_waits', new.rowid, 'insert', NULL, json_object('node_key', new.node_key, 'flow_id', new.flow_id, 'status', new.status, 'archival', new.archival, 'released_at', new.released_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_occurrence_spawned_waits_update AFTER UPDATE ON occurrence_spawned_waits BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'occurrence_spawned_waits', new.rowid, 'update', json_object('node_key', old.node_key, 'flow_id', old.flow_id, 'status', old.status, 'archival', old.archival, 'released_at', old.released_at), json_object('node_key', new.node_key, 'flow_id', new.flow_id, 'status', new.status, 'archival', new.archival, 'released_at', new.released_at), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;

CREATE TRIGGER undo_journal_occurrence_spawned_waits_delete AFTER DELETE ON occurrence_spawned_waits BEGIN
    INSERT INTO undo_journal (gesture_id, source, table_name, row_id, operation, before_image, after_image, written_at)
    SELECT gesture_id, source, 'occurrence_spawned_waits', old.rowid, 'delete', json_object('node_key', old.node_key, 'flow_id', old.flow_id, 'status', old.status, 'archival', old.archival, 'released_at', old.released_at), NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
      FROM undo_context WHERE id = 1 AND suppressed = 0;
END;
