"""Writes python/arlesh/models.py: pydantic models generated from the Rust types' JSON Schema.

The schema comes from the built extension (``arlesh._native.json_schema()``), which schemars
generates from the same Rust types the core serialises, so the models cannot drift from the wire
format. CI runs this with ``--check`` and fails when the committed file differs from a fresh one.

    uv run python generate_models.py           # rewrite the models
    uv run python generate_models.py --check   # exit 1 if they are stale
"""

from __future__ import annotations

import importlib.machinery
import importlib.util
import json
import subprocess
import sys
import tempfile
from pathlib import Path
from types import ModuleType

HERE = Path(__file__).parent


def _load_native() -> ModuleType:
    """The built extension, loaded on its own.

    Not through ``import arlesh``: the package imports the models this script writes, so a model
    the Rust side has just added would make the package fail to import before it could be generated.
    """
    spec = importlib.util.find_spec("arlesh")
    locations = list(spec.submodule_search_locations or []) if spec else []
    for location in locations:
        for candidate in sorted(Path(location).glob("_native*.so")):
            loader = importlib.machinery.ExtensionFileLoader("arlesh._native", str(candidate))
            native_spec = importlib.util.spec_from_loader("arlesh._native", loader)
            if native_spec is None:
                continue
            module = importlib.util.module_from_spec(native_spec)
            loader.exec_module(module)
            return module
    raise SystemExit("arlesh._native is not built: run `uv run maturin develop --uv` first.")


_native = _load_native()
TARGET = HERE / "python" / "arlesh" / "models.py"
HEADER = '''# mypy: disable-error-code="assignment"
"""Pydantic models for every type the arlesh API takes or returns.

GENERATED by crates/arlesh-py/generate_models.py from the Rust types' JSON Schema. Do not edit:
change the Rust type, rebuild, and regenerate. CI fails when this file is stale.

The generator writes a union-typed field's default as its JSON value (``{"kind": "manual"}``),
which pydantic validates into the model but mypy reads as the wrong type; the directive above
silences exactly that.
"""
'''


def _name_pairs(node: object) -> None:
    """Titles every fixed pair of integers ``IdPair``, and reads every naive datetime as a
    ``datetime``, in place.

    The generator names an untitled inline schema after the field holding it, singularised — so
    ``ForkedTemplate.tasks``, a list of old-to-new id pairs, would take the name ``Task`` from the
    real Task model. A title gives the pairs a name of their own.
    """
    if isinstance(node, dict):
        # chrono's NaiveDateTime is `partial-date-time`, which the generator reads as a plain
        # string. A naive `datetime` is what it is, and what pydantic reads and writes it as.
        if node.get("format") == "partial-date-time":
            node["format"] = "date-time"
        if node.get("prefixItems") and node.get("minItems") == node.get("maxItems") == 2:
            node["title"] = "IdPair"
        for value in node.values():
            _name_pairs(value)
    elif isinstance(node, list):
        for value in node:
            _name_pairs(value)


def _camel(snake: str) -> str:
    """``part_of_day`` as ``PartOfDay``."""
    return "".join(part.capitalize() for part in snake.split("_"))


def _tag_of(variant: dict[str, object]) -> str | None:
    """The constant a tagged-union variant's tag holds, or ``None`` for an untagged one."""
    properties = variant.get("properties")
    if not isinstance(properties, dict):
        return None
    for schema in properties.values():
        if isinstance(schema, dict) and isinstance(schema.get("const"), str):
            return str(schema["const"])
    return None


def _variant_name(variant: object) -> str | None:
    """What names a union variant: its tag's constant, or the one key of an externally tagged
    object (``{"window": …}``). ``None`` for a plain value."""
    if not isinstance(variant, dict):
        return None
    tag = _tag_of(variant)
    if tag is not None:
        return tag
    required = variant.get("required")
    if variant.get("type") == "object" and isinstance(required, list) and len(required) == 1:
        return str(required[0])
    return None


def _name_variants(definitions: dict[str, dict[str, object]]) -> dict[str, list[str]]:
    """Titles every object variant of a union ``<Union><Tag>``, in place, and answers the variant
    names of each union whose every variant is tagged — ``ScopeKey`` is
    ``ScopeKeySeason | ScopeKeyMonth | …``.

    Untitled, the generator would number them (``ScopeKey1``…), and a number says nothing.
    """
    unions: dict[str, list[str]] = {}
    for name, schema in definitions.items():
        variants = schema.get("oneOf")
        if not isinstance(variants, list):
            continue
        names: list[str | None] = []
        for variant in variants:
            tag = _variant_name(variant)
            if tag is None or not isinstance(variant, dict):
                names.append(None)
                continue
            variant["title"] = name + _camel(tag)
            names.append(name + _camel(tag))
        if names and all(variant_name is not None for variant_name in names):
            unions[name] = [str(variant_name) for variant_name in names]
    return unions


def _aliases(unions: dict[str, list[str]], body: str) -> str:
    """A type alias for every union the generator inlined rather than declared."""
    lines = [
        f"{name}: TypeAlias = {' | '.join(names)}"
        for name, names in sorted(unions.items())
        if f"class {name}(" not in body
    ]
    if not lines:
        return ""
    return "\n\n# The tagged unions, by the names the Rust types have.\n" + "\n".join(lines) + "\n"


def generate() -> str:
    """The models module, as text."""
    document = json.loads(_native.json_schema())
    _name_pairs(document)
    unions = _name_variants(document["$defs"])
    with tempfile.TemporaryDirectory() as scratch:
        schema = Path(scratch) / "arlesh.schema.json"
        output = Path(scratch) / "models.py"
        schema.write_text(json.dumps(document, indent=2, sort_keys=True))
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(schema),
                "--input-file-type",
                "jsonschema",
                "--output",
                str(output),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.11",
                "--use-annotated",
                "--use-standard-collections",
                "--use-union-operator",
                "--use-schema-description",
                "--use-field-description",
                "--use-title-as-name",
                "--set-default-enum-member",
                "--output-datetime-class",
                "datetime",
                "--enum-field-as-literal",
                "one",
                "--collapse-root-models",
                "--disable-timestamp",
                "--formatters",
                "ruff-format",
                "ruff-check",
            ],
            check=True,
        )
        body = output.read_text()
    body = body.replace("from typing import ", "from typing import TypeAlias, ", 1)
    return HEADER + "\n" + body + _aliases(unions, body)


def main() -> int:
    """Rewrites the models, or with ``--check`` reports whether they are stale."""
    fresh = generate()
    if "--check" in sys.argv[1:]:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != fresh:
            print(f"{TARGET} is stale: run `uv run python generate_models.py`.", file=sys.stderr)
            return 1
        print(f"{TARGET.name} is current.")
        return 0
    TARGET.write_text(fresh)
    print(f"wrote {TARGET} ({len(json.loads(_native.json_schema())['$defs'])} schema types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
