//! Renders `baseline/schema.sql` from the migration chain.
//!
//! The chain runs on an empty in-memory database with the SQLite this build links, and the result
//! is read back, so the text is exactly what the chain stored in `sqlite_master`. Tables come
//! first, then their rows, then indexes, views and triggers: rows are loaded before any trigger
//! exists, as they were when the migrations seeded them, so nothing is journaled.
//!
//! `examples/generate_baseline.rs` writes the file; a test here fails when the file differs.

use std::borrow::Cow;

use sqlx::migrate::Migrator;
use sqlx::sqlite::SqlitePoolOptions;
use sqlx::{Row, SqlitePool};

use super::BASELINE_VERSION;
use crate::database::MIGRATOR;

/// The file's opening comment, naming the migration the baseline stands for.
fn header() -> String {
    format!(
        "-- GENERATED by `cargo run -p arlesh-core --example generate_baseline`. Do not edit.\n\
-- The schema and seed data that migrations 1 through {BASELINE_VERSION} leave behind: a fresh\n\
-- database is created from this in one pass, then migrations 1..={BASELINE_VERSION} are recorded as\n\
-- applied. See src/database/baseline.rs. A unit test fails on any difference from the chain.\n\n"
    )
}

/// The baseline text, from the chain run on an empty database.
pub async fn render() -> anyhow::Result<String> {
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect("sqlite::memory:")
        .await?;
    let through_baseline = Migrator {
        migrations: Cow::Owned(
            MIGRATOR
                .iter()
                .filter(|migration| migration.version <= BASELINE_VERSION)
                .cloned()
                .collect(),
        ),
        ignore_missing: false,
        locking: true,
        no_tx: false,
    };
    through_baseline.run(&pool).await?;

    let mut text = header();
    let tables = definitions(
        &pool,
        "type = 'table' AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\' AND name <> '_sqlx_migrations'",
    )
    .await?;
    for (_, sql) in &tables {
        text.push_str(&format!("{sql};\n"));
    }
    for (name, _) in &tables {
        text.push_str(&rows(&pool, name).await?);
    }
    text.push_str(&sequences(&pool).await?);
    for (_, sql) in definitions(&pool, "type IN ('index', 'view', 'trigger')").await? {
        text.push_str(&format!("{sql};\n"));
    }
    Ok(text)
}

/// `(name, sql)` of every schema object matching `condition`, in the order the chain created them.
async fn definitions(pool: &SqlitePool, condition: &str) -> anyhow::Result<Vec<(String, String)>> {
    let query = format!(
        "SELECT name, sql FROM sqlite_master WHERE sql IS NOT NULL AND {condition} ORDER BY rowid"
    );
    sqlx::query(&query)
        .fetch_all(pool)
        .await?
        .iter()
        .map(|row| Ok((row.try_get("name")?, row.try_get("sql")?)))
        .collect()
}

/// One `INSERT` per row of `table`, in rowid order, each value as SQLite's own `quote()` spells it.
async fn rows(pool: &SqlitePool, table: &str) -> anyhow::Result<String> {
    let columns: Vec<String> =
        sqlx::query_scalar("SELECT name FROM pragma_table_info(?) ORDER BY cid")
            .bind(table)
            .fetch_all(pool)
            .await?;
    let quoted = columns
        .iter()
        .map(|column| format!("quote(\"{column}\")"))
        .collect::<Vec<_>>()
        .join(" || ',' || ");
    let names = columns
        .iter()
        .map(|column| format!("\"{column}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let values: Vec<String> =
        sqlx::query_scalar(&format!("SELECT {quoted} FROM \"{table}\" ORDER BY rowid"))
            .fetch_all(pool)
            .await?;
    Ok(values
        .iter()
        .map(|row| format!("INSERT INTO \"{table}\" ({names}) VALUES ({row});\n"))
        .collect())
}

/// Restores `sqlite_sequence`, which the inserts above advanced only as far as the rows that
/// survived: a table that once held higher ids keeps counting from them.
async fn sequences(pool: &SqlitePool) -> anyhow::Result<String> {
    let counters = sqlx::query("SELECT name, seq FROM sqlite_sequence ORDER BY name")
        .fetch_all(pool)
        .await?;
    let mut text = String::from("DELETE FROM sqlite_sequence;\n");
    for counter in &counters {
        let name: String = counter.try_get("name")?;
        let sequence: i64 = counter.try_get("seq")?;
        text.push_str(&format!(
            "INSERT INTO sqlite_sequence (name, seq) VALUES ('{name}', {sequence});\n"
        ));
    }
    Ok(text)
}
