//! Writes `baseline/schema.sql`: the schema and seed data that migrations `1..=BASELINE_VERSION`
//! leave behind, so a fresh database can be created in one pass instead of by running them.
//!
//! ```text
//! cargo run -p arlesh-core --example generate_baseline            # rewrite the file
//! cargo run -p arlesh-core --example generate_baseline -- --check # fail if it is out of date
//! ```
//!
//! It runs the real chain on an empty in-memory database with the SQLite this build links, then
//! reads the result back, so the text is exactly what the chain stored in `sqlite_master`. Tables
//! come first, then their rows, then indexes, views and triggers: rows are loaded before any
//! trigger exists, as they were when the migrations seeded them, so nothing is journaled.

use std::borrow::Cow;
use std::path::PathBuf;
use std::process::ExitCode;

use arlesh_core::database::baseline::BASELINE_VERSION;
use arlesh_core::database::MIGRATOR;
use sqlx::migrate::Migrator;
use sqlx::sqlite::SqlitePoolOptions;
use sqlx::{Row, SqlitePool};

const HEADER: &str = "-- GENERATED by `cargo run -p arlesh-core --example generate_baseline`. Do not edit.\n\
-- The schema and seed data that migrations 0001 through 0094 leave behind: a fresh database is\n\
-- created from this in one pass, then migrations 1..=94 are recorded as applied. See\n\
-- src/database/baseline.rs. CI regenerates it and fails on any difference.\n\n";

#[tokio::main(flavor = "current_thread")]
async fn main() -> anyhow::Result<ExitCode> {
    let generated = generate().await?;
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("baseline/schema.sql");
    if std::env::args().any(|argument| argument == "--check") {
        if std::fs::read_to_string(&path)? == generated {
            return Ok(ExitCode::SUCCESS);
        }
        eprintln!(
            "{} is out of date with the migrations. Regenerate it:\n  cargo run -p arlesh-core --example generate_baseline",
            path.display()
        );
        return Ok(ExitCode::FAILURE);
    }
    std::fs::write(&path, generated)?;
    Ok(ExitCode::SUCCESS)
}

/// The baseline text, from the chain run on an empty database.
async fn generate() -> anyhow::Result<String> {
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect("sqlite::memory:")
        .await?;
    let through_baseline = Migrator {
        migrations: Cow::Owned(
            MIGRATOR
                .iter()
                .filter(|migration| migration.version <= BASELINE_VERSION)
                .cloned()
                .collect(),
        ),
        ignore_missing: false,
        locking: true,
        no_tx: false,
    };
    through_baseline.run(&pool).await?;

    let mut text = String::from(HEADER);
    let tables = definitions(&pool, "type = 'table' AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\' AND name <> '_sqlx_migrations'").await?;
    for (_, sql) in &tables {
        text.push_str(&format!("{sql};\n"));
    }
    for (name, _) in &tables {
        text.push_str(&rows(&pool, name).await?);
    }
    text.push_str(&sequences(&pool).await?);
    for (_, sql) in definitions(&pool, "type IN ('index', 'view', 'trigger')").await? {
        text.push_str(&format!("{sql};\n"));
    }
    Ok(text)
}

/// `(name, sql)` of every schema object matching `condition`, in the order the chain created them.
async fn definitions(pool: &SqlitePool, condition: &str) -> anyhow::Result<Vec<(String, String)>> {
    let query = format!(
        "SELECT name, sql FROM sqlite_master WHERE sql IS NOT NULL AND {condition} ORDER BY rowid"
    );
    sqlx::query(&query)
        .fetch_all(pool)
        .await?
        .iter()
        .map(|row| Ok((row.try_get("name")?, row.try_get("sql")?)))
        .collect()
}

/// One `INSERT` per row of `table`, in rowid order, each value as SQLite's own `quote()` spells it.
async fn rows(pool: &SqlitePool, table: &str) -> anyhow::Result<String> {
    let columns: Vec<String> =
        sqlx::query_scalar("SELECT name FROM pragma_table_info(?) ORDER BY cid")
            .bind(table)
            .fetch_all(pool)
            .await?;
    let quoted = columns
        .iter()
        .map(|column| format!("quote(\"{column}\")"))
        .collect::<Vec<_>>()
        .join(" || ',' || ");
    let names = columns
        .iter()
        .map(|column| format!("\"{column}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let values: Vec<String> =
        sqlx::query_scalar(&format!("SELECT {quoted} FROM \"{table}\" ORDER BY rowid"))
            .fetch_all(pool)
            .await?;
    Ok(values
        .iter()
        .map(|row| format!("INSERT INTO \"{table}\" ({names}) VALUES ({row});\n"))
        .collect())
}

/// Restores `sqlite_sequence`, which the inserts above advanced only as far as the rows that
/// survived: a table that once held higher ids keeps counting from them.
async fn sequences(pool: &SqlitePool) -> anyhow::Result<String> {
    let counters = sqlx::query("SELECT name, seq FROM sqlite_sequence ORDER BY name")
        .fetch_all(pool)
        .await?;
    let mut text = String::from("DELETE FROM sqlite_sequence;\n");
    for counter in &counters {
        let name: String = counter.try_get("name")?;
        let sequence: i64 = counter.try_get("seq")?;
        text.push_str(&format!(
            "INSERT INTO sqlite_sequence (name, seq) VALUES ('{name}', {sequence});\n"
        ));
    }
    Ok(text)
}
