"""Type stubs for the native extension. Use the `arlesh` package, not this module."""

from collections.abc import Awaitable
from os import PathLike

class NativeError(Exception): ...

class NativeDatabase:
    @property
    def client(self) -> str | None: ...
    def call(self, request: str) -> Awaitable[str]: ...
    def serve_mcp(self, host: str, port: int) -> Awaitable[int]: ...
    def stop_mcp(self) -> Awaitable[None]: ...
    def close(self) -> Awaitable[None]: ...

def open(
    path: str | PathLike[str], client: str | None, force: bool
) -> Awaitable[NativeDatabase]: ...
def rule(request: str) -> str: ...
def json_schema() -> str: ...
