//! The JSON Schema of every type the Python API takes or returns.
//!
//! One document with every type under `$defs`, generated by `schemars` from the Rust types
//! themselves — the same derives a FastAPI service built on these bindings reads for its OpenAPI.
//! The Python half's pydantic models are generated from this document
//! (`crates/arlesh-py/generate_models.py`), and CI regenerates them and fails on any difference,
//! so a Rust type cannot change without its Python model changing with it.

use arlesh_core::{
    domains::model::Domain,
    error::WireErrorKind,
    flows::{
        cycles::ForkedTemplate,
        model::{
            Flow, FlowGoal, FlowRecurrence, FlowTask, HabitIteration, InstanceTiming,
            MaterializedFlow,
        },
        rules::cycle_grid::CycleLevel,
    },
    infos::model::Info,
    mindmap::model::MindmapLoad,
    scopes::{model::Scope, resolve::ResolvedScope},
    tasks::{
        gestures::StatusStepOutcome,
        model::{
            Commitment, Dependency, Expectation, Goal, SpawnedWait, Task, TaskStatus,
            TaskWithBlockers,
        },
        rules::lifecycle::{ArchivalResult, CommitmentState, DerivedState, Resolution, Timing},
    },
};
use schemars::{generate::SchemaSettings, JsonSchema, SchemaGenerator};
use serde_json::{json, Map, Value};

use crate::{request::Request, rules::Rule, rules::StatusAfter};

/// Adds `T` and everything it refers to to `generator`.
fn add<T: JsonSchema>(generator: &mut SchemaGenerator) {
    generator.subschema_for::<T>();
}

/// The document: `$defs` holding every request, rule call and answer type.
pub(crate) fn document() -> Value {
    let mut generator = SchemaGenerator::new(SchemaSettings::draft2020_12());
    // What Python sends.
    add::<Request>(&mut generator);
    add::<Rule>(&mut generator);
    // What it gets back.
    add::<MindmapLoad>(&mut generator);
    add::<TaskWithBlockers>(&mut generator);
    add::<Task>(&mut generator);
    add::<Goal>(&mut generator);
    add::<Commitment>(&mut generator);
    add::<Expectation>(&mut generator);
    add::<SpawnedWait>(&mut generator);
    add::<Info>(&mut generator);
    add::<Domain>(&mut generator);
    add::<Flow>(&mut generator);
    add::<FlowGoal>(&mut generator);
    add::<FlowTask>(&mut generator);
    add::<FlowRecurrence>(&mut generator);
    add::<MaterializedFlow>(&mut generator);
    add::<ForkedTemplate>(&mut generator);
    add::<Dependency>(&mut generator);
    add::<StatusStepOutcome>(&mut generator);
    add::<StatusAfter>(&mut generator);
    add::<Scope>(&mut generator);
    add::<ResolvedScope>(&mut generator);
    add::<Timing>(&mut generator);
    add::<Resolution>(&mut generator);
    add::<ArchivalResult>(&mut generator);
    add::<DerivedState>(&mut generator);
    add::<CommitmentState>(&mut generator);
    add::<InstanceTiming>(&mut generator);
    add::<HabitIteration>(&mut generator);
    add::<TaskStatus>(&mut generator);
    add::<CycleLevel>(&mut generator);
    add::<WireErrorKind>(&mut generator);
    let definitions: Map<String, Value> = generator.take_definitions(true);
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Arlesh",
        "description": "Every type the arlesh Python API takes or returns.",
        "$defs": definitions,
    })
}
